name: Setup SSH on Windows Runner

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: windows-latest
    steps:
      - name: Install OpenSSH Server
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
          Start-Service sshd
          Set-Service -Name sshd -StartupType 'Automatic'
          netsh advfirewall firewall add rule name="OpenSSH-Server-In-TCP" dir=in action=allow protocol=TCP localport=22

      - name: Display SSH connection details
        run: |
          echo "SSH Setup Complete"
          echo "Username: $env:USERNAME"
          echo "IP Address: $(hostname -I)"
